--- Create the DEPARTMENT table if it does not exist
CREATE TABLE IF NOT EXISTS DEPARTMENT (
EMPLOYEE_ID TEXT,
NAME TEXT,
DEPARTMENT_ID TEXT,
MANAGER_ID TEXT,
SALARY REAL
);

-- INSERT SAMPLE DATA INTO THE DEPARTMENT TABLE
INSERT INTO DEPARTMENT (EMPLOYEE_ID, NAME, DEPARTMENT_ID, MANAGER_ID,
('100', 'BOBBY CHARLTON', '090', '100', 75000),
('101', 'GEORGE BEST', '090', '100', 70000),
('102', 'DENIS LAW', '090', '100', 65000),
('103', 'ERIC CANTONA', '091', '103', 80000),
('104', 'RYAN GIGGS', '091', '103', 75000),
('105', 'PAUL SCHOLLES', '091', '103', 70000),
('106', 'DAVID BECKHAM', '092', '106', 85000),
('107', 'WAYNE ROONEY', '092', '106', 80000),
('108', 'CRISTIANO RONALDO', '092', '106', 90000);

-- QUERY TO CALCULATE THE SUM OF EACH SALARY IN EACH DEPARTMENT
SELECT DEPARTMENT_ID, AS "Department Code",
SUM(SALARY) AS "Total Salary"
FROM DEPARTMENT
GROUP BY DEPARTMENT_ID;

--- QUERY TO COUNT THE NUMBER OF EMPLOYEES IN EACH DEPARTMENT
SELECT DEPARTMENT_ID, AS "Department Code",
COUNT(EMPLOYEE_ID) AS "Number of Employees"
FROM DEPARTMENT
GROUP BY DEPARTMENT_ID;

--- QUERY TO CALCULATE THE SUM SALARY IN EACH DEPARTMENT
SELECT DEPARTMENT_ID, AS "Department Code",
SUM(SALARY) AS "Total Salary"
FROM DEPARTMENT
GROUP BY DEPARTMENT_ID;

--- QUERY TO SUM THE SALARY OF EMPLOYEES WITH A SPECIFIC MANAGER
SELECT department_id AS "Department Code",
SUM(salary) AS "Total Salary"
FROM department
WHERE manager_id = '103'
GROUP BY department_id;

-- QUERY TO FIND DEPARTMENTS WITH MORE THAN 2EMPLOYEES
SELECT department_id, COUNT(*) AS "Number of Employees"
FROM department
GROUP BY department_id
HAVING COUNT(*) > 2;
